### ISSUE TITLE
System.InvalidOperationException in Xamarin Forms (iOS)

### ISSUE THREAD

**Issue by sahil-khanna** [hyperledger/aries-framework-dotnet#142]
**Describe the bug**
I have set up a Xamarin Forms app for iOS. In the initial configuration (to register a container, an exception is thrown. Below is the source code. The sample project that I have built is available [here](https://drive.google.com/drive/folders/1NVvY5_VseptZZaXNHqDq7Nmsf_9t4wBb?usp=sharing)

```
public partial class App : Application
    {
        internal static IContainer Container { get; private set; }

        public App()
        {
            InitializeComponent();

            RegisterContainer();

            MainPage = new MainPage();
        }

        private void RegisterContainer()
        {
            var services = new ServiceCollection();
            services.AddLogging();

            // Initialize Autofac
            var builder = new ContainerBuilder();

            builder.RegisterAssemblyTypes(typeof(IConnectionService).Assembly)
                .AsImplementedInterfaces();
            builder.RegisterType<HttpClient>().AsSelf();

            builder.Populate(services);

            // Build the final container
            Container = builder.Build();    // *** EXCEPTION HERE ***
        }
    }
```

**To Reproduce**
1. Setup the Xamarin Forms project
2. Run the app on the simulator
3. The app crashes at the line `Container = builder.Build();`

**Expected behavior**
The app should be able to build the Container, just like it does correctly for Android

**Screenshots**
https://drive.google.com/file/d/1aNyNp64g6j9aw0SmtMmJG-PuEHMVFSvr/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: iOS, Mac
 - .NET Core SDK 5.0.100-rc.2.20479.15

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - OS: iOS 14.1

**Additional context**
No exception is raised in Android

**Comment by tmarkovski** [comment]
The app is set to strip all symbols, when no code is using them. You don't need this in Debug mode. You can turn off linking in iOS project options. Set it do "Don't link" or "SDK Only"

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1280118/99859378-e3e01b00-2b5d-11eb-9712-edc2edcb3b4f.png">

**Comment by sahil-khanna** [comment]
Thanks, @tmarkovski. Changing the Link behavior to "Don't link" solved the issue. The agent provisions successfully.

Referring to the code [here](https://github.com/hyperledger/aries-framework-dotnet/blob/c23c008cca3f56d4f5699d9e8934a2e00273dfe8/samples/xamarin-forms/AFMobileSample/MainPage.xaml.cs#L61) to create a new invitation, I'm getting the below error

`CS1503: Argument 1: cannot convert from 'Hyperledger.Aries.Agents.AgentContext' to 'AgentFramework.Core.Contracts.IAgentContext'`

Screenshot [here](https://drive.google.com/file/d/17-1OslT5rVCVuzJ1IJa8ps_lftCcC03z/view?usp=sharing)

Can you advise on this, please?

**Comment by sahil-khanna** [comment]
> Thanks, @tmarkovski. Changing the Link behavior to "Don't link" solved the issue. The agent provisions successfully.
> 
> Referring to the code [here](https://github.com/hyperledger/aries-framework-dotnet/blob/c23c008cca3f56d4f5699d9e8934a2e00273dfe8/samples/xamarin-forms/AFMobileSample/MainPage.xaml.cs#L61) to create a new invitation, I'm getting the below error
> 
> `CS1503: Argument 1: cannot convert from 'Hyperledger.Aries.Agents.AgentContext' to 'AgentFramework.Core.Contracts.IAgentContext'`
> 
> Screenshot [here](https://drive.google.com/file/d/17-1OslT5rVCVuzJ1IJa8ps_lftCcC03z/view?usp=sharing)
> 
> Can you advise on this, please?

This seems to work in the [Aries MobileAgent Xamarin](https://github.com/hyperledger/aries-mobileagent-xamarin)
