### ISSUE TITLE
Travis CI is no longer supported

### ISSUE THREAD

**Issue by ryjones** [hyperledger/aries-framework-dotnet#148]
Travis CI has changed how open source projects are supported, and Hyperledger can no longer build there. I suggest Azure Pipelines or GitHub Actions as a replacement.

**Comment by tmarkovski** [comment]
Thanks. I'll look into GitHub actions - last time I tried with Azure Pipelines, build would randomly timeout due to memory cap.

**Comment by tmarkovski** [comment]
@ryjones We will need to merge in #149 without CI validation, to continue with this. I am working on adding gh actions to the CI in a separate PR.
