### ISSUE TITLE
Cred def response object is not parsable.

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger/aries-framework-dotnet#167]
Aries cloud agent issue credential to osma mobile agent.when osma mobile agent accept credential,code breaks in file (../blob/master/src/Hyperledger.Aries/Ledger/DefaultLedgerService.cs)
when calling method "await IndyLedger.ParseGetCredDefResponseAsync(res);".Getting error : ledger item not found -309 error indy exception.
This seems res obj is not parsable from indy-sdk method.could you pls suggest how this res object needs to be pass.req and res object is attached.
[req.txt](https://github.com/hyperledger/aries-framework-dotnet/files/5949322/req.txt)
[res.txt](https://github.com/hyperledger/aries-framework-dotnet/files/5949323/res.txt)

**Comment by juvebogdan** [comment]
@Shweta-hlf I am getting something similar in osma mobile agent when i click accept.

An unmapped error with the code '309' was returned by the SDK.

Did you managed to solve this?

**Comment by Shweta-hlf** [comment]
could you please clear ./indy-client folder from your mobile device.That can be hidden file and it's point to wrong genesis url.

**Comment by juvebogdan** [comment]
Thanks a lot. That fixed it
