### ISSUE TITLE
Build error on WebAgent asp core 

### ISSUE THREAD

**Issue by rkirandas** [hyperledger/aries-framework-dotnet#223]
On building the Asp core Web Agent in samples, I am getting some errors due to missing namespace Hyperledger.Aries.Features.DidExchange, IConnectionService Interface is not correctly included namespace etc. the errors are mentioned below on the attachement

![Capture 1](https://user-images.githubusercontent.com/62564910/171614289-e6e9fd59-e52d-4cce-99e1-210ca3506614.PNG)
![Capture 2](https://user-images.githubusercontent.com/62564910/171614312-f3095cd5-caab-4904-a9c8-207d742a7d0f.PNG)

Kindly give guidance

**Comment by x0axz** [comment]
Check that all of the nuget packages are loaded correctly, then clear the project and restart Visual Studio, then try to run the project to check whether the problem has been fixed.

**Comment by mturetchi** [comment]
There have been some major changes in recent commits, and samples projects have not been adapted. 
For example IConnectionService was moved from Hyperledger.Aries.Features.DidExchange -> Hyperledger.Aries.Features.Handshakes.Connection

**Comment by rkirandas** [comment]
@mturetchi 
One help, Can you please take a look on this Issue
https://github.com/hyperledger/aries-mobile-agent-xamarin/issues/63#issuecomment-1151900982
