### ISSUE TITLE
EdgeConsoleClient sends the request to only localhost:5000 all the time

### ISSUE THREAD

**Issue by airoasis** [hyperledger/aries-framework-dotnet#40]
**Describe the bug**
If I run the MediatorAgentService in the localhost:6000, and execute the EdgeConsoleClient with the EndpointUri = "localhost:6000", EdgeClient sends the request to localhost:5000

**To Reproduce**
1. Open MediatorAgentService/Startup.cs and update options.EndpointUri = "http://localhost:6000/"
2. Open MediatorAgentService/Properties/launchSettings.json and update the port number from 5000 to 6000
3. Open EdgeConsoleClient/Program.cs, and update the port number from 5000 to 6000
4. Run the mediator
5. Run the edge client

Actually, the call to CreateInvitationAsync fails because it sends the request localhost:5000

**Expected behavior**
Run without error

**Comment by tmarkovski** [comment]
@airoasis When you run the services locally, both mediator and agent provision a wallet for that service. Running it subsequently, doesn't provision the wallet again, so your old changes were preserved.
To fix this, simply remove all wallets under `~/.indy_client/wallet` folder and run the updates services again.

**Comment by airoasis** [comment]
I have resolved the issue. Thank you very much.
