### ISSUE TITLE
Service 'web-agent-1' failed to build by running ./start-web-agents.sh

### ISSUE THREAD

**Issue by x0axz** [hyperledger/aries-framework-dotnet#72]
The issue is when i run ./start-web-agents.sh command get the following errors. 

I have windows 10 and using linux containters. And also using MINGW64.

```
Step 7/16 : RUN dotnet restore "WebAgent.csproj" -s "https://api.nuget.org/v3/index.json"
---> Running in ea3cb8f5afe5
A compatible installed .NET Core SDK for global.json version [3.1.101] from [/src/global.json] was not found
Install the [3.1.101] .NET Core SDK or update [/src/global.json] with an installed .NET Core SDK:
3.0.101 [/usr/share/dotnet/sdk]
ERROR: Service 'web-agent-1' failed to build: The command '/bin/sh -c dotnet restore "WebAgent.csproj" -s "https://api.nuget.org/v3/index.json"' returned a non-zero code: 145
```

Here is the screenshots : https://www.dropbox.com/sh/wzmmvb4rrint5wh/AACCftqvuM1TcPz7PMeldJ38a?dl=0

**Comment by x0axz** [comment]
@michaeldboyd Comments on this Issue: "looks like we need to add a step to the dockerfile above that installs dotnet sdk 3.1.101"

**Comment by tmarkovski** [comment]
@x0axz Updating the `docker/web-agent.dockerfile` to use image `streetcred/dotnet-indy:1.14.2`  will give you the needed net core runtime.
Here's what the images contain
https://github.com/streetcred-id/docker/

**Comment by x0axz** [comment]
@tmarkovski Thank u so much :)

**Comment by x0axz** [comment]
@tmarkovski I build Docker Image and now using it to Run Web Agent. And also rename samples/aspnetcore to samples/example.
After running ./start-web-agents.sh, it returned this error (public urls open and also able to connect it with osma).

```
Step 7/16 : RUN dotnet restore "WebAgent.csproj"     -s "https://api.nuget.org/v3/index.json"
 ---> Running in 840274b7a0be
A compatible installed .NET Core SDK for global.json version [3.1.101] from [/src/global.json] was not found
Install the [3.1.101] .NET Core SDK or update [/src/global.json] with an installed .NET Core SDK:
  3.1.200 [/usr/share/dotnet/sdk]
ERROR: Service 'web-agent-1' failed to build: The command '/bin/sh -c dotnet restore "WebAgent.csproj"     -s "https://api.nuget.org/v3/index.json"' returned a non-zero code: 145
```

**Comment by x0axz** [comment]
Changed the SDK Version to 3.1.200.
Changed the Text in .cshtml files. Also remove the Name Generator and add a Name (Static) Instead.
```

Startup.cs(36,87): error CS1012: Too many characters in character literal [/src/samples/example-agent/WebAgent.csproj]

Build FAILED.

Startup.cs(36,87): error CS1012: Too many characters in character literal [/src/samples/example-agent/WebAgent.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:18.26
ERROR: Service 'web-agent-1' failed to build: The command '/bin/sh -c dotnet build "WebAgent.csproj" -c Release -o /app' returned a non-zero code: 1
Creating network "ariesdotnet_agent_net" with driver "bridge"
ERROR: Pool overlaps with other one on this address space
```

**Comment by x0axz** [comment]
SOLVED!!!
For SKD Incompatibility, I changed the` SDK version` to `3.1.200` (which is installed on my laptop) in `global.json`.
And for Docker error (Pool Overlaps) , simply run, ` docker network pune`, which will remove the unnecessary containers.
